# Generated by Django 2.2.24 on 2022-03-08 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appearance', '0004_auto_20220308_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='fontLink',
            field=models.CharField(db_index=True, default='', help_text='Font link URL.', max_length=2000, unique=True, verbose_name='font Link URL'),
            preserve_default=False,
        ),
    ]
