# Generated by Django 2.2.24 on 2022-03-06 17:55

import colorful.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appearance', '0004_auto_20220306_0905'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='bdtColor',
            field=colorful.fields.RGBColorField(default='ffffff', help_text='The RGB color values for Head text color.', verbose_name='body text color.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='theme',
            name='bgColor',
            field=colorful.fields.RGBColorField(default='ffffff', help_text='The RGB color values for background page color.', verbose_name='Backgroud pages color.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='theme',
            name='htColor',
            field=colorful.fields.RGBColorField(default='ffffff', help_text='The RGB color values for help text color.', verbose_name='Help text color.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='theme',
            name='mtColor',
            field=colorful.fields.RGBColorField(default='ffffff', help_text='The RGB color values for main text color.', verbose_name='main text color.'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='theme',
            name='stylesheet',
            field=models.TextField(blank=True, help_text='The CSS stylesheet to change the appearance of the differentuser interface elements.', verbose_name='Stylesheet'),
        ),
    ]
