# Generated by Django 2.2.24 on 2022-03-06 18:02

import colorful.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appearance', '0005_auto_20220306_1755'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theme',
            name='bdtColor',
        ),
        migrations.RemoveField(
            model_name='theme',
            name='bgColor',
        ),
        migrations.RemoveField(
            model_name='theme',
            name='htColor',
        ),
        migrations.RemoveField(
            model_name='theme',
            name='mainColor',
        ),
        migrations.RemoveField(
            model_name='theme',
            name='mtColor',
        ),
        migrations.RemoveField(
            model_name='theme',
            name='secondColor',
        ),
        migrations.RemoveField(
            model_name='theme',
            name='thirdColor',
        ),
        migrations.AddField(
            model_name='theme',
            name='bg_Main_Menu',
            field=colorful.fields.RGBColorField(default='ffffff', help_text='The RGB color values for main menu background color.', verbose_name='Background color main menu.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='theme',
            name='bg_Main_Menu_at',
            field=colorful.fields.RGBColorField(default='ffffff', help_text='The RGB color values for active of main menu top bar.', verbose_name='Active color main menu'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='theme',
            name='bg_bd',
            field=colorful.fields.RGBColorField(default='ffffff', help_text='The RGB color values for background body.', verbose_name='Background body color'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='theme',
            name='ct_bg_color',
            field=colorful.fields.RGBColorField(default='ffffff', help_text='The RGB color values for background content color.', verbose_name='Content background color'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='theme',
            name='dd_menu',
            field=colorful.fields.RGBColorField(default='ffffff', help_text='The RGB color values for drop down text menu.', verbose_name='Drop down menu text color'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='theme',
            name='hl_color',
            field=colorful.fields.RGBColorField(default='ffffff', help_text='The RGB color values for highlight.', verbose_name='Highlight color'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='theme',
            name='sc_bt_button',
            field=colorful.fields.RGBColorField(default='ffffff', help_text='The RGB color values for second button.', verbose_name='Second background button'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='theme',
            name='sc_tx_color',
            field=colorful.fields.RGBColorField(default='ffffff', help_text='The RGB color values for second text.', verbose_name='Second text body color'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='theme',
            name='tx_main',
            field=colorful.fields.RGBColorField(default='ffffff', help_text='The RGB color values for main text.', verbose_name='Main text color'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='theme',
            name='tx_menu',
            field=colorful.fields.RGBColorField(default='ffffff', help_text='The RGB color values for menu text color.', verbose_name='Menu text color'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='theme',
            name='stylesheet',
            field=models.TextField(blank=True, help_text='The CSS stylesheet to change the appearance of the different user interface elements.', verbose_name='Stylesheet'),
        ),
    ]
