# Generated by Django 2.2.24 on 2022-03-07 12:17

import colorful.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appearance', '0006_auto_20220306_1802'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theme',
            name='bg_Main_Menu',
        ),
        migrations.RemoveField(
            model_name='theme',
            name='bg_Main_Menu_at',
        ),
        migrations.RemoveField(
            model_name='theme',
            name='bg_bd',
        ),
        migrations.RemoveField(
            model_name='theme',
            name='ct_bg_color',
        ),
        migrations.RemoveField(
            model_name='theme',
            name='dd_menu',
        ),
        migrations.RemoveField(
            model_name='theme',
            name='hl_color',
        ),
        migrations.RemoveField(
            model_name='theme',
            name='sc_bt_button',
        ),
        migrations.RemoveField(
            model_name='theme',
            name='sc_tx_color',
        ),
        migrations.RemoveField(
            model_name='theme',
            name='tx_main',
        ),
        migrations.RemoveField(
            model_name='theme',
            name='tx_menu',
        ),
        migrations.AddField(
            model_name='theme',
            name='bdtColor',
            field=colorful.fields.RGBColorField(default='ffffff', help_text='The RGB color values for Head text color.', verbose_name='body text color.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='theme',
            name='bgColor',
            field=colorful.fields.RGBColorField(default='ffffff', help_text='The RGB color values for background page color.', verbose_name='Backgroud pages color.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='theme',
            name='htColor',
            field=colorful.fields.RGBColorField(default='ffffff', help_text='The RGB color values for help text color.', verbose_name='Help text color.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='theme',
            name='mainColor',
            field=colorful.fields.RGBColorField(default='ffffff', help_text='The RGB color values for first main menu bar color.', verbose_name='Main Color'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='theme',
            name='mtColor',
            field=colorful.fields.RGBColorField(default='ffffff', help_text='The RGB color values for main text color.', verbose_name='main text color.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='theme',
            name='secondColor',
            field=colorful.fields.RGBColorField(default='ffffff', help_text='The RGB color values for second main menu color.', verbose_name='Second Color'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='theme',
            name='thirdColor',
            field=colorful.fields.RGBColorField(default='ffffff', help_text='The RGB color values for third color. It should be a color darker than the main color.', verbose_name='Third Color'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='theme',
            name='stylesheet',
            field=models.TextField(blank=True, help_text='The CSS stylesheet to change the appearance of the differentuser interface elements.', verbose_name='Stylesheet'),
        ),
    ]
