# Generated by Django 2.2.24 on 2022-03-18 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appearance', '0006_remove_theme_fontlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='font',
            field=models.CharField(db_index=True, default=' ', help_text='Font name in google api font.', max_length=2000, unique=True, verbose_name='Font'),
            preserve_default=False,
        ),
    ]
