# Generated by Django 2.2.24 on 2022-03-07 12:30

import colorful.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appearance', '0007_auto_20220307_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='frameColor',
            field=colorful.fields.RGBColorField(default='ffffff', help_text='The RGB color values for frame background color.', verbose_name='frame background color.'),
            preserve_default=False,
        ),
    ]
