# Generated by Django 2.2.24 on 2022-03-18 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appearance', '0007_theme_font'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='font',
            field=models.CharField(db_index=True, help_text='Font name in google font.', max_length=2000, verbose_name='Font'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='logoLink',
            field=models.CharField(db_index=True, help_text='Logo link URL.', max_length=2000, verbose_name='Logo Link URL'),
        ),
    ]
