# Generated by Django 2.2.24 on 2022-03-07 13:02

import colorful.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appearance', '0008_theme_framecolor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theme',
            name='mainColor',
        ),
        migrations.RemoveField(
            model_name='theme',
            name='secondColor',
        ),
        migrations.RemoveField(
            model_name='theme',
            name='thirdColor',
        ),
        migrations.AddField(
            model_name='theme',
            name='hlColor',
            field=colorful.fields.RGBColorField(default='ffffff', help_text='The RGB color values for Highlight color.', verbose_name='Highlight Color'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='theme',
            name='logoLink',
            field=models.CharField(db_index=True, default='https://i.imgur.com/MRSWq6d.png', help_text='Logo Link.', max_length=300, unique=True, verbose_name='Label'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='theme',
            name='mmColor',
            field=colorful.fields.RGBColorField(default='ffffff', help_text='The RGB color values for first main menu bar color.', verbose_name='First Main menu Color'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='theme',
            name='smmColor',
            field=colorful.fields.RGBColorField(default='ffffff', help_text='The RGB color values for second main menu color.', verbose_name='Second Main menu Color'),
            preserve_default=False,
        ),
    ]
