# Generated by Django 2.2.24 on 2022-03-07 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appearance', '0009_auto_20220307_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='logoLink',
            field=models.CharField(db_index=True, help_text='Logo Link.', max_length=2000, unique=True, verbose_name='Logo Link'),
        ),
    ]
