# Generated by Django 2.2.24 on 2022-03-08 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appearance', '0010_auto_20220307_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='logoLink',
            field=models.CharField(db_index=True, help_text='Logo link URL.', max_length=2000, unique=True, verbose_name='Logo Link URL'),
        ),
    ]
